package com.doganmehmet.app.enums;

public enum AuditType {
    CREATED, LOGIN, LOGOUT, INCORRECT_PASSWORD, BANNED,
    TRANSFER_SUCCESS, TRANSFER_FAILED,
    DEPOSIT_SUCCESS, DEPOSIT_FAILED,
    WITHDRAWAL_SUCCESS, WITHDRAWAL_FAILED
}
